server:
  shutdown: graceful
  port: 8001

spring:
  application:
    name: order-taker
  main:
    banner-mode: off
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
